# -*- coding: utf-8 -*-
"""Visual Transformer and CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j67OvOqLnWmwJAuoaMLi9YGqG8avJ-uO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from sklearn.model_selection import train_test_split

dataset = '/content/drive/MyDrive/Vegetable_Images/train'


full_dataset = tf.keras.utils.image_dataset_from_directory(
    dataset,
    labels='inferred',
    label_mode='int',
    image_size=(128, 128), # You can adjust the image size
    interpolation='nearest',
    batch_size=None # Load images without batching for splitting
)

max_samples = 600   # adjust as needed (e.g., 500–1000 for faster scikit-learn training)

images = []
labels = []
i = 0  # Initialize the counter

for img, label in full_dataset: # Use the correct dataset variable
    if i >= max_samples:
        break
    images.append(img.numpy())
    labels.append(label.numpy())
    i += 1 # Increment the counter

X = np.array(images)
y = np.array(labels)

idx = np.random.randint(0, len(X))
plt.figure(figsize=(4, 4))
plt.imshow(X[idx])
plt.title(f"Label: {y[idx]}")
plt.show()

"""# Resampling and Augmentation"""

# Split the data into training and testing sets
# Use stratify=y to ensure the class distribution is similar in both train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2, # Adjust the test size as needed
    random_state=42, # Set a random state for reproducibility
    stratify=y
)
print('X.shape', X.shape)
print('y.shape', y.shape)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)
print("y_train count:", np.bincount(y_train))
print("y_test count:", np.bincount(y_test))

# === FIX: ensure labels are 1-D ints and capture class names ===
y = y.reshape(-1).astype('int32')
y_train = y_train.reshape(-1).astype('int32')
y_test  = y_test.reshape(-1).astype('int32')

try:
    class_names = list(getattr(full_dataset, 'class_names', []))
    if class_names and len(class_names) != len(np.unique(y)):
        # fallback if mismatch
        class_names = [str(i) for i in range(len(np.unique(y)))]
except Exception:
    class_names = [str(i) for i in range(len(np.unique(y)))]

n_classes = len(np.unique(y))
print("n_classes:", n_classes, "class_names:", class_names if len(class_names)<=10 else class_names[:10])

from imblearn.over_sampling import RandomOverSampler

def oversample_with_imblearn(X, y):
    # Get original shape
    N, H, W, C = X.shape

    # Flatten for imblearn (samples, features)
    X_flat = X.reshape(N, -1)

    # Create oversampler
    ros = RandomOverSampler()

    # Perform oversampling
    X_res, y_res = ros.fit_resample(X_flat, y)

    # Reshape back to image form
    X_res = X_res.reshape(-1, H, W, C)

    return X_res, y_res

np.unique(y_train, return_counts=True)



"""# Create balanced subsample"""

X_train_bal, y_train_bal = oversample_with_imblearn(X_train, y_train)

print("Before balancing:", np.bincount(y_train))
print("After balancing: ", np.bincount(y_train_bal))

"""# Models

# Multimodal Cifar
"""

'''# -----------------------------------------------------------
# Build two-input CNN model
# -----------------------------------------------------------
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *

dropout_rate = 0.2
n_classes  = np.unique(y_train).shape[0]

# Image input and CNN
img_input = Input(shape=X_train.shape[1:], name="image_input")

x = Conv2D(8, (3, 3), activation='relu', padding='same')(img_input)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = BatchNormalization()(x)
x = Dropout(dropout_rate)(x)

x = Conv2D(16, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = BatchNormalization()(x)
x = Dropout(dropout_rate)(x)

x = Conv2D(32, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = BatchNormalization()(x)
x = Dropout(dropout_rate)(x)

x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D(pool_size=(2, 2))(x)

x = GlobalAveragePooling2D()(x)

# Type input (scalar: 0 or 1)
type_input = Input(shape=(1,), name="type_input")

# Concatenate CNN features with type
concat = Concatenate()([x, type_input])

output = Dense(n_classes, activation='softmax')(concat)

# Final model
model = Model(inputs=[img_input, type_input], outputs=output)
model.summary()'''

'''from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

epochs = 15
batch_size = 256
initial_learning_rate = 0.01

optimizer = Adam(learning_rate=initial_learning_rate)

model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)'''

'''from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define the image generator with augmentation options
datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,      # Rotate images randomly
    width_shift_range=0.2,  # Randomly shift the width of images
    height_shift_range=0.2, # Randomly shift the height of images
    zoom_range=0.1,         # Randomly zoom
)'''

'''# Generate dummy type_input for train and test sets
# Assuming type_input is a scalar (e.g., 0 or 1), let's use 0 for all for now.
type_train = np.zeros((X_train_bal.shape[0], 1))
type_test = np.zeros((X_test.shape[0], 1))

# Custom generator to combine image batches from ImageDataGenerator with the type input
def custom_multimodal_generator(image_data_generator, type_data_array):
    # Determine the constant type value for this generator based on the first element of type_data_array.
    # This assumes type_data_array contains a constant value for all samples in this dataset (train or test).
    constant_type_value = type_data_array[0][0]

    for X_batch, y_batch in image_data_generator:
        # Create a type_batch of the correct size with the constant value
        type_batch = np.full((X_batch.shape[0], 1), constant_type_value, dtype='float32')
        # Yield a tuple of inputs (image, type) and the corresponding labels
        yield (X_batch, type_batch), y_batch

# Instantiate image data generators
train_image_generator = datagen.flow(
    X_train_bal, y_train_bal,
    batch_size=batch_size,
    shuffle=True,
)

validation_image_generator = datagen.flow(
    X_test, y_test,
    batch_size=batch_size,
    shuffle=False,
)

# Instantiate custom multimodal generators
train_generator_multimodal = custom_multimodal_generator(train_image_generator, type_train)
validation_generator_multimodal = custom_multimodal_generator(validation_image_generator, type_test)
'''

'''history = model.fit(
    train_generator_multimodal,
    epochs=15,
    validation_data=validation_generator_multimodal,
    verbose=1,
    callbacks=[early_stopping]
)'''

'''from sklearn.metrics import classification_report, confusion_matrix

# Predictions
y_test_pred = model.predict([X_test, type_test]).argmax(axis=1)

# Training plots
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
fig.suptitle('CNN with Type Input', fontsize=16)

# Left: loss curves
axes[0].plot(history.history['loss'], label='Training Loss')
axes[0].plot(history.history['val_loss'], label='Validation Loss')
axes[0].set_title('Training and Validation Loss')
axes[0].set_xlabel('Epochs')
axes[0].set_ylabel('Loss')
axes[0].legend()

# Right: confusion matrix
cm = confusion_matrix(y_test, y_test_pred)
sns.heatmap(cm, annot=True, fmt='d', ax=axes[1], vmin=0,
            annot_kws={"size": 12}, cmap='nipy_spectral')
axes[1].set_title('Confusion Matrix (Test Data)')
axes[1].set_xlabel('Predicted Label')
axes[1].set_ylabel('True Label')

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

# Classification report
from sklearn.metrics import classification_report
report = classification_report(y_test, y_test_pred)
print(report)'''

"""# Cifar"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

dropout_rate = 0.1

n_classes  = np.unique(y_train_bal).shape[0]

# Create model
model = Sequential([
    Input(shape=X_train_bal.shape[1:]),

    Conv2D(8, (3, 3), activation='relu', padding='same'),
    MaxPooling2D(),
    BatchNormalization(),
    Dropout(dropout_rate),

    Conv2D(16, (3, 3), activation='relu', padding='same'),
    MaxPooling2D(),
    BatchNormalization(),
    Dropout(dropout_rate),

    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D(),

    GlobalAveragePooling2D(),

    Dense(n_classes, activation='softmax'),
])

# Define the optimizer with a custom learning rate
optimizer = Adam(learning_rate=0.01)

# Compile model
model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Early stopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',  # Monitor validation loss
    patience=10,          # Stop after 5 epochs without improvement
    restore_best_weights=True  # Restore the best weights after stopping
)

# Display model summary
model.summary()

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define the image generator with augmentation options
datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,      # Rotate images randomly
    width_shift_range=0.2,  # Randomly shift the width of images
    height_shift_range=0.2, # Randomly shift the height of images
    zoom_range=0.1,         # Randomly zoom
)

# === FIX: clean evaluation helpers ===
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.preprocessing.image import ImageDataGenerator

def evaluate_with_rescale(model, X_test, y_test, class_names=None, rescale=1./255, batch_size=128, verbose=0, title="Fixed Evaluation"):
    """Evaluate a CNN trained with ImageDataGenerator(rescale=...) on raw arrays.
    Uses NO augmentation and preserves order (shuffle=False).
    """
    test_gen = ImageDataGenerator(rescale=rescale)
    flow = test_gen.flow(X_test, y_test, batch_size=batch_size, shuffle=False)
    y_pred = model.predict(flow, verbose=verbose).argmax(axis=1)
    print(title)
    print(classification_report(y_test, y_pred, target_names=class_names if class_names and len(class_names)==len(np.unique(y_test)) else None, digits=4))
    return y_pred

def evaluate_direct(model, X_test_encoded, y_test, class_names=None, verbose=0, title="Fixed Evaluation (encoded)"):
    y_pred = model.predict(X_test_encoded, verbose=verbose).argmax(axis=1)
    print(title)
    print(classification_report(y_test, y_pred, target_names=class_names if class_names and len(class_names)==len(np.unique(y_test)) else None, digits=4))
    return y_pred

history = model.fit(
    datagen.flow(
        X_train_bal, y_train_bal,
        batch_size=256,
        shuffle=True,
        ),
    epochs=15,
    validation_data=datagen.flow(
        X_test, y_test
        ),
    verbose=1,
    callbacks=[early_stopping]
)

from sklearn.metrics import classification_report, confusion_matrix

# Predictions
y_train_pred = model.predict(X_train).argmax(axis=1)
y_test_pred  = model.predict(X_test).argmax(axis=1)

# Confusion matrices
cm_train = confusion_matrix(y_train, y_train_pred)
cm_test  = confusion_matrix(y_test, y_test_pred)

# 2x2 subplots
fig, axes = plt.subplots(2, 2, figsize=(9, 7))

# Top-left: Training and Validation Loss
axes[0, 0].plot(history.history['loss'], label='Training Loss')
axes[0, 0].plot(history.history['val_loss'], label='Validation Loss')
axes[0, 0].set_title('Training and Validation Loss')
axes[0, 0].set_xlabel('Epochs')
axes[0, 0].set_ylabel('Loss')
axes[0, 0].legend()

# Top-right: Training and Validation Accuracy
axes[0, 1].plot(history.history['accuracy'], label='Training Accuracy')
axes[0, 1].plot(history.history['val_accuracy'], label='Validation Accuracy')
axes[0, 1].set_title('Training and Validation Accuracy')
axes[0, 1].set_xlabel('Epochs')
axes[0, 1].set_ylabel('Accuracy')
axes[0, 1].legend()

# Bottom-left: Confusion Matrix (Training)
sns.heatmap(cm_train, annot=True, fmt='d', ax=axes[1, 0], vmin=0, annot_kws={"size": 12})
axes[1, 0].set_title('Confusion Matrix (Training Data)')
axes[1, 0].set_xlabel('Predicted Label')
axes[1, 0].set_ylabel('True Label')

# Bottom-right: Confusion Matrix (Test)
sns.heatmap(cm_test, annot=True, fmt='d', ax=axes[1, 1], vmin=0, annot_kws={"size": 12})
axes[1, 1].set_title('Confusion Matrix (Test Data)')
axes[1, 1].set_xlabel('Predicted Label')
axes[1, 1].set_ylabel('True Label')

plt.tight_layout()
plt.show()

# Print classification report for test data
print("Classification Report (Test Data):")
print(classification_report(y_test, y_test_pred))

"""# Transfer Learned Model"""

from tensorflow.keras.applications import EfficientNetV2M
from tensorflow.keras.applications import MobileNetV2

# Load EfficientNetB3 without top layer
base_model = EfficientNetV2M(weights='imagenet', include_top=False, input_shape=(128, 128, 3))
#base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(128, 128, 3))
base_model.trainable = False

# Display model summary
#base_model.summary()

# Extract features using the untrainable EfficientNetB3
X_train_encoded = base_model.predict(X_train, verbose=1)
X_test_encoded = base_model.predict(X_test, verbose=1)

print("X_train_encoded.shape:", X_train_encoded.shape)
print("X_test_encoded.shape: ", X_test_encoded.shape)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import *

n_classes  = np.unique(y_train).shape[0]

# Create a classification head
input_encoded = Input(shape=X_train_encoded.shape[1:])
x = Flatten()(input_encoded)
x = Dropout(0.5)(x)
outputs = Dense(n_classes, activation='softmax')(x)

# Build the model
model = Model(inputs=input_encoded, outputs=outputs)

model.summary()

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers.schedules import ExponentialDecay, PolynomialDecay

# define training parameters
epochs     = 50
batch_size = 256

optimizer = Adam(
    learning_rate=0.001,
)

# Compile model
model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Early stopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',  # Monitor validation loss
    patience=20,          # Stop after 5 epochs without improvement
    restore_best_weights=True  # Restore the best weights after stopping
)

history = model.fit(
    X_train_encoded, y_train,
    epochs=epochs,
    batch_size=batch_size,
    shuffle=True,
    validation_data=(X_test_encoded, y_test),
    verbose=1,
    callbacks=[early_stopping]
)

# === FIX: Proper evaluation for encoded features (no augmentation mismatch) ===
_ = evaluate_direct(model, X_test_encoded, y_test, class_names=class_names, verbose=0, title="Fixed Evaluation: Feature Model #1")
eval

from sklearn.metrics import classification_report, confusion_matrix

# Predictions
y_train_pred = model.predict(X_train_encoded).argmax(axis=1)
y_test_pred  = model.predict(X_test_encoded).argmax(axis=1)

# Confusion matrices
cm_train = confusion_matrix(y_train, y_train_pred)
cm_test  = confusion_matrix(y_test, y_test_pred)

# 2x2 subplots
fig, axes = plt.subplots(2, 2, figsize=(9, 7))

# Top-left: Training and Validation Loss
axes[0, 0].plot(history.history['loss'], label='Training Loss')
axes[0, 0].plot(history.history['val_loss'], label='Validation Loss')
axes[0, 0].set_title('Training and Validation Loss')
axes[0, 0].set_xlabel('Epochs')
axes[0, 0].set_ylabel('Loss')
axes[0, 0].legend()

# Top-right: Training and Validation Accuracy
axes[0, 1].plot(history.history['accuracy'], label='Training Accuracy')
axes[0, 1].plot(history.history['val_accuracy'], label='Validation Accuracy')
axes[0, 1].set_title('Training and Validation Accuracy')
axes[0, 1].set_xlabel('Epochs')
axes[0, 1].set_ylabel('Accuracy')
axes[0, 1].legend()

# Bottom-left: Confusion Matrix (Training)
sns.heatmap(cm_train, annot=True, fmt='d', ax=axes[1, 0], vmin=0, annot_kws={"size": 12})
axes[1, 0].set_title('Confusion Matrix (Training Data)')
axes[1, 0].set_xlabel('Predicted Label')
axes[1, 0].set_ylabel('True Label')

# Bottom-right: Confusion Matrix (Test)
sns.heatmap(cm_test, annot=True, fmt='d', ax=axes[1, 1], vmin=0, annot_kws={"size": 12})
axes[1, 1].set_title('Confusion Matrix (Test Data)')
axes[1, 1].set_xlabel('Predicted Label')
axes[1, 1].set_ylabel('True Label')

plt.tight_layout()
plt.show()

# Print classification report for test data
print("Classification Report (Test Data):")
print(classification_report(y_test, y_test_pred))

"""#Visual Transformers"""

!pip install torch
!pip install transformers
!pip install evaluate

import torch
import evaluate
import numpy as np
from transformers import (ViTImageProcessor, ViTForImageClassification, TrainingArguments, Trainer)
from datasets import load_dataset

dataset_transformer = '/content/drive/MyDrive/Vegetable_Images/train'


full_dataset_ViT = load_dataset(
    "imagefolder",
    data_dir=dataset_transformer
)

"""#Initialize Image Processor"""

model_checkpoint = "google/vit-base-patch16-224-in21k"
image_processor = ViTImageProcessor.from_pretrained(model_checkpoint)

#Extract label mappings
labels = full_dataset_ViT["train"].features["label"].names
label2id = {label: str(i) for i, label in enumerate(labels)}
id2label = {str(i): label for label, i in label2id.items()}

model = ViTForImageClassification.from_pretrained(
    model_checkpoint,
    num_labels=len(labels),
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True,
)

"""# Preprocess the Images"""

def transform(example_batch):
  inputs = image_processor([x.convert("RGB") for x in example_batch["image"]], return_tensors="pt")
  inputs["labels"] = example_batch["label"]
  return inputs

"""# Define data collator and metrics"""

def collate_fn(batch):
  return{
      "pixel_values": torch.stack([x["pixel_values"] for x in batch]),
      "labels": torch.tensor([x["labels"] for x in batch])
  }

metric = evaluate.load("accuracy")

def compute_metrics(p):
    return metric.compute(
        predictions=np.argmax(p.predictions, axis=1),
        references=p.label_ids
        )

"""# Training arguments"""

from transformers.trainer_utils import IntervalStrategy

training_args = TrainingArguments(
    output_dir="./vit-classifier-results",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    # evaluation_strategy=IntervalStrategy.EPOCH, # Removed due to TypeError
    # save_strategy="epoch", # Removed due to potential TypeError or inconsistency
    learning_rate=5e-5,
    num_train_epochs=3,
    logging_steps=10,
    remove_unused_columns=False,
    metric_for_best_model="accuracy",
    weight_decay=0.0001,
    # load_best_model_at_the_end=True, # Removed due to TypeError
    fp16=torch.cuda.is_available()
)

"""#Run the trainer"""

splits = full_dataset_ViT["train"].train_test_split(test_size=0.2, seed=42)
train_dataset = splits["train"]
eval_dataset = splits["test"]

# Apply the transform function to the datasets
train_dataset = train_dataset.with_transform(transform)
eval_dataset = eval_dataset.with_transform(transform)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=collate_fn,
    compute_metrics=compute_metrics,
)

trainer.train()

df = pd.DataFrame(trainer.state.log_history)
df['epoch'].head(10)

import matplotlib.pyplot as plt
train_logs = df[df['loss'].notna()]
eval_logs = df[df["epoch"].notna()]

#3. Create the plot
plt.figure(figsize=(10, 5))
plt.plot(train_logs['step'], train_logs['loss'], label='Training Loss')
plt.plot(eval_logs['step'], eval_logs['epoch'], label='Validation Loss')
plt.xlabel('Training Step')
plt.ylabel('Loss Value')
plt.title('ViT Training and Validation Loss Over Time')
plt.legend()
plt.grid(True)
plt.show()

'''final_eval_results = trainer.evaluate()
#print(final_eval_results)

for key, value in final_eval_results.items():
    print(f"{key}: {value}")'''

"""# Save interupted ViT model"""

trainer.save_model("./my_interrupted_vit_model")

"""#Force-Save a Checkpoint"""

# Create a manual checkpoint folder
trainer.save_model("./vit-classifier-results/checkpoint-custom")

"""#Look at Raw Numbers"""

import pandas as pd
#convert internal trainer logs into clean table

df = pd.DataFrame(trainer.state.log_history)
print(df.head(10))

"""# Plot training loss curve"""

train_logs = [log for log in trainer.state.log_history if "loss" in log]

steps = [log["step"] for log in train_logs]
losses = [log["loss"] for log in train_logs]

plt.figure(figsize=(10, 5))
plt.plot(steps, losses, label="Training Loss")
plt.xlabel("Step")
plt.ylabel("Loss")
plt.title("ViT Training Loss Curve Over Time")
plt.legend()
plt.grid(True)
plt.show()

"""# Plot the Evaluation accuracy"""

eval_logs = [log for log in trainer.state.log_history if "eval_accuracy" in log]

if eval_logs:
    eval_steps = [log["step"] for log in eval_logs]
    accuracies = [log["eval_accuracy"] for log in eval_logs]

    plt.figure(figsize=(10, 5))
    plt.plot(eval_steps, accuracies, label="Validation Accuracy")
    plt.xlabel("Step")
    plt.ylabel("Accuracy")
    plt.title("ViT Validation Accuracy per Epoch")
    plt.legend()
    plt.grid(True)
    plt.show()
else:
    print("No evaluation metrics found yet. Finish at least one full epoch or run trainer.evaluate()!")

"""# Resume training after interruption"""

# Tells the traineer to pick up exactly where I left off
trainer.train(resume_from_checkpoint="./vit-classifier-results/checkpoint-custom")

"""Note regarding data split consistency. If seed=42, dataset splits are locked in and perfectly reproducible meaning if you interrupt and resume, the data sequence remains exactly the same preventing data leakage."""